package com.silver.zoomer.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "user")
public class User {
    private String id;
    private String name;
    private String username;

    public User() {
    }

    public User(final String id, final String name, final String username) {
        this.id = id;
        this.name = name;
        this.username = username;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }

    public void setId(final String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getName() {
        return this.name;
    }

    public void setName(final String name) {
        this.name = name;
    }

    @DynamoDBAttribute
    public String getUsername() {
        return this.username;
    }

    public void setUsername(final String username) {
        this.username = username;
    }
}
