version: '3.5'

services:
    dynamodb:
        image:  amazon/dynamodb-local
        hostname: dynamodb
        restart: always
        volumes:
            -  dynamodb_data:/home/dynamodblocal/data
        ports:
            - 4566:8000
volumes:
  dynamodb_data:
    driver: local
